### ISSUE TITLE
Search module 1 results in errors

### ISSUE THREAD

**Issue by Mistermay** [WoollyinWalesIT/jomres#102]
Hi,

When installing the Search module 1 on a clean installation I get these errors:

`jquery-ui.js?v=1484045816:580 Uncaught TypeError: $.widget.extend is not a function
    at $.(anonymous function).(anonymous function)._createWidget (https://XXXX.com/jomres/javascript/jquery-ui.js?v=1484045816:580:27)
    at new $.(anonymous function).(anonymous function) (https://XXXX.com/jomres/javascript/jquery-ui.js?v=1484045816:376:9)
    at HTMLSpanElement.<anonymous> (https://XXXX.com/jomres/javascript/jquery-ui.js?v=1484045816:531:30)
    at Function.each (https://XXXX.com/media/jui/js/jquery.min.js:2:2881)
    at $.init.each (https://XXXX.com/media/jui/js/jquery.min.js:2:846)
    at $.init.$.fn.(anonymous function) [as tooltip] (https://XXXX.com/jomres/javascript/jquery-ui.js?v=1484045816:523:9)
    at HTMLDocument.<anonymous> (https://XXXX.com/:62:38)
    at i (https://XXXX.com/media/jui/js/jquery.min.js:2:27449)
    at Object.fireWith [as resolveWith] (https://XXXX.com/media/jui/js/jquery.min.js:2:28213)
    at Function.ready (https://XXXX.com/media/jui/js/jquery.min.js:2:30006)`

Is this a known bug?

**Comment by alibarthi** [comment]
Please open a ticket on https://tickets.jomres.net/ , this is not a problem that we can replicate so we`ll need to have a look at your site.

**Comment by Mistermay** [comment]
@alibarthi I found out that its the Vina Camera Image Slider that causes this issue. Maybe this steers you in the right direction. Its not your extension but you do have CSS added to your files related to this extension
